from news_ch.news_crawler.thenewslens import TheNewsLens
from news_ch.news_crawler.anue import Anue
from news_ch.news_crawler.apple import Apple
from news_ch.news_crawler.newtalk import NewTalk
from news_ch.news_crawler.setn import SETN
from news_ch.news_crawler.pts import PTS
from news_ch.news_crawler.united import United
from news_ch.news_crawler.libertytimes import LibertyTimes
from news_ch.news_crawler.ithome import iThome
from news_ch.news_crawler.ettoday import ETtoday
from news_ch.news_crawler.cna import CNA
from news_ch.news_crawler.chinatimes import ChinaTimes
from news_ch.news_crawler.tvbs import TVBS
from news_ch.news_crawler.cp import CP
from news_ch.news_crawler.infotalk import InfoTalk
from news_ch.news_crawler.tvbs_save_money import TVBS_SaveMoney
